### PR TITLE
avoid error when app not installed

### LINKED ISSUE #362: [Bug]: Error in log "App Related Resources - error Related Resource Provider NotFound Error" when acces to contact / circles app
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After installing the Contacts app, every time we access these 6 messages appear in the log.

Error | related_resources | RelatedResourceProviderNotFoundException thrown: OCA\RelatedResources\Exceptions\RelatedResourceProviderNotFoundException thrown: OCA\RelatedResources\Exceptions\RelatedResourceProviderNotFound | Feb 22, 2024, 2:03:24 PM |  

Error | related_resources | RelatedResourceProviderNotFoundException thrown: OCA\RelatedResources\Exceptions\RelatedResourceProviderNotFoundException thrown: OCA\RelatedResources\Exceptions\RelatedResourceProviderNotFound | Feb 22, 2024, 2:03:24 PM |  

Error | related_resources | RelatedResourceProviderNotFoundException thrown: OCA\RelatedResources\Exceptions\RelatedResourceProviderNotFoundException thrown: OCA\RelatedResources\Exceptions\RelatedResourceProviderNotFound | Feb 22, 2024, 2:03:24 PM |  

Error | related_resources | RelatedResourceProviderNotFoundException thrown: OCA\RelatedResources\Exceptions\RelatedResourceProviderNotFoundException thrown: OCA\RelatedResources\Exceptions\RelatedResourceProviderNotFound | Feb 22, 2024, 2:03:24 PM |  

Error | related_resources | RelatedResourceProviderNotFoundException thrown: OCA\RelatedResources\Exceptions\RelatedResourceProviderNotFoundException thrown: OCA\RelatedResources\Exceptions\RelatedResourceProviderNotFound | Feb 22, 2024, 2:03:24 PM |  

Error | related_resources | RelatedResourceProviderNotFoundException thrown: OCA\RelatedResources\Exceptions\RelatedResourceProviderNotFoundException thrown: OCA\RelatedResources\Exceptions\RelatedResourceProviderNotFound

After testing, we have detected that if we have the Deck, Calendar and Talk apps installed and enabled, it does not give this error message. We think that the app does not correctly detect that these providers are not installed. Tested with NextCloud 28.0.1, 28.0.2 and 28.0.3 RC1 y 28.0.3 RC2.

Test with php8.1 and php 8.2 with the same result and error messages.

### Steps to reproduce

1. Install and enable contacts app.
2. Acess contact app.
3. Logs messages with error 

### Expected behavior

No errors logs.

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "next03t.canal-sur.interno"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.2.5",
        "overwrite.cli.url": "https:\/\/next03t.canal-sur.interno\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5
        },
        "htaccess.RewriteBase": "\/",
        "default_phone_region": "ES",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpdebug": true,
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpstreamoptions": {
            "ssl": {
                "verify_peer": false,
                "verify_peer_name": false
            }
        },
        "logtimezone": "Europe\/Madrid",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "logfile_audit": "\/var\/log\/nextcloud\/nextcloud.log",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "tempdirectory": "\/nextcloud-datos\/tmp\/",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.release.channel": "stable",
        "maintenance_window_start": 17,
        "allow_local_remote_servers": true,
        "session_lifetime": 86400,
        "remember_login_cookie_lifetime": "0",
        "session_keepalive": "false",
        "preview_max_x": 1024,
        "preview_max_y": 768,
        "preview_max_scale_factor": 1,
        "allow_local_address": true
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contacts: 5.5.2
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_accesscontrol: 1.18.0
  - files_fulltextsearch: 28.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - fulltextsearch: 28.0.0
  - fulltextsearch_elasticsearch: 28.0.0
  - groupfolders: 16.0.3
  - impersonate: 1.15.0
  - jitsi: 0.18.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - onlyoffice: 9.0.0
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - support: 1.11.0
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_ldap: 1.19.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - bruteforcesettings: 2.8.0
  - encryption: 2.16.0
  - files_external: 1.20.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - suspicious_login: 6.0.0
  - twofactor_totp: 10.0.0-beta.2
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"PAXCmVnyZ97bx0jdiqYo","level":1,"time":"2024-02-23T12:10:31+01:00","remoteAddr":"10.236.138.4","user":"admin","app":"admin_audit","method":"POST","url":"/settings/apps/enable","message":"App \"contacts\" enabled","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0","version":"28.0.2.5","data":{"app":"admin_audit"}}
{"reqId":"FlIjUT6YVOU7Znd7CLl7","level":3,"time":"2024-02-23T12:10:59+01:00","remoteAddr":"10.236.138.4","user":"admin","app":"related_resources","method":"GET","url":"/ocs/v2.php/apps/related_resources/related/account?itemId=admin&resourceType=talk&limit=5&format=json","message":"Exception thrown: OCA\\RelatedResources\\Exceptions\\RelatedResourceProviderNotFound","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0","version":"28.0.2.5","exception":{"Exception":"OCA\\RelatedResources\\Exceptions\\RelatedResourceProviderNotFound","Message":"","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/related_resources/lib/Service/RelatedService.php","line":173,"function":"getRelatedResourceProvider","class":"OCA\\RelatedResources\\Service\\RelatedService","type":"->"},{"file":"/var/www/nextcloud/apps/related_resources/lib/Service/RelatedService.php","line":127,"function":"retrieveRelatedToItem","class":"OCA\\RelatedResources\\Service\\RelatedService","type":"->"},{"file":"/var/www/nextcloud/apps/related_resources/lib/Controller/ApiController.php","line":108,"function":"getRelatedToItem","class":"OCA\\RelatedResources\\Service\\RelatedService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"getRelatedResources","class":"OCA\\RelatedResources\\Controller\\ApiController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":65,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/ocs/v2.php","line":23,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/related_resources/lib/Service/RelatedService.php","Line":605,"message":"","exception":{},"CustomMessage":"Exception thrown: OCA\\RelatedResources\\Exceptions\\RelatedResourceProviderNotFound"}}
{"reqId":"jnhCAAJsNCcrWphlcGBP","level":3,"time":"2024-02-23T12:10:59+01:00","remoteAddr":"10.236.138.4","user":"admin","app":"related_resources","method":"GET","url":"/ocs/v2.php/apps/related_resources/related/account?itemId=admin&resourceType=calendar&limit=5&format=json","message":"Exception thrown: OCA\\RelatedResources\\Exceptions\\RelatedResourceProviderNotFound","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0","version":"28.0.2.5","exception":{"Exception":"OCA\\RelatedResources\\Exceptions\\RelatedResourceProviderNotFound","Message":"","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/related_resources/lib/Service/RelatedService.php","line":173,"function":"getRelatedResourceProvider","class":"OCA\\RelatedResources\\Service\\RelatedService","type":"->"},{"file":"/var/www/nextcloud/apps/related_resources/lib/Service/RelatedService.php","line":127,"function":"retrieveRelatedToItem","class":"OCA\\RelatedResources\\Service\\RelatedService","type":"->"},{"file":"/var/www/nextcloud/apps/related_resources/lib/Controller/ApiController.php","line":108,"function":"getRelatedToItem","class":"OCA\\RelatedResources\\Service\\RelatedService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"getRelatedResources","class":"OCA\\RelatedResources\\Controller\\ApiController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":65,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/ocs/v2.php","line":23,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/related_resources/lib/Service/RelatedService.php","Line":605,"message":"","exception":{},"CustomMessage":"Exception thrown: OCA\\RelatedResources\\Exceptions\\RelatedResourceProviderNotFound"}}
{"reqId":"PPp6NDRaQWyotiNUV31a","level":3,"time":"2024-02-23T12:10:59+01:00","remoteAddr":"10.236.138.4","user":"admin","app":"related_resources","method":"GET","url":"/ocs/v2.php/apps/related_resources/related/account?itemId=admin&resourceType=deck&limit=5&format=json","message":"Exception thrown: OCA\\RelatedResources\\Exceptions\\RelatedResourceProviderNotFound","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0","version":"28.0.2.5","exception":{"Exception":"OCA\\RelatedResources\\Exceptions\\RelatedResourceProviderNotFound","Message":"","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/related_resources/lib/Service/RelatedService.php","line":173,"function":"getRelatedResourceProvider","class":"OCA\\RelatedResources\\Service\\RelatedService","type":"->"},{"file":"/var/www/nextcloud/apps/related_resources/lib/Service/RelatedService.php","line":127,"function":"retrieveRelatedToItem","class":"OCA\\RelatedResources\\Service\\RelatedService","type":"->"},{"file":"/var/www/nextcloud/apps/related_resources/lib/Controller/ApiController.php","line":108,"function":"getRelatedToItem","class":"OCA\\RelatedResources\\Service\\RelatedService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"getRelatedResources","class":"OCA\\RelatedResources\\Controller\\ApiController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":65,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/ocs/v2.php","line":23,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/related_resources/lib/Service/RelatedService.php","Line":605,"message":"","exception":{},"CustomMessage":"Exception thrown: OCA\\RelatedResources\\Exceptions\\RelatedResourceProviderNotFound"}}
{"reqId":"B0IgSJGRK9uciuTVOc73","level":3,"time":"2024-02-23T12:10:59+01:00","remoteAddr":"10.236.138.4","user":"admin","app":"related_resources","method":"GET","url":"/ocs/v2.php/apps/related_resources/related/account?itemId=admin&resourceType=talk&limit=5&format=json","message":"Exception thrown: OCA\\RelatedResources\\Exceptions\\RelatedResourceProviderNotFound","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0","version":"28.0.2.5","exception":{"Exception":"OCA\\RelatedResources\\Exceptions\\RelatedResourceProviderNotFound","Message":"","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/related_resources/lib/Service/RelatedService.php","line":173,"function":"getRelatedResourceProvider","class":"OCA\\RelatedResources\\Service\\RelatedService","type":"->"},{"file":"/var/www/nextcloud/apps/related_resources/lib/Service/RelatedService.php","line":127,"function":"retrieveRelatedToItem","class":"OCA\\RelatedResources\\Service\\RelatedService","type":"->"},{"file":"/var/www/nextcloud/apps/related_resources/lib/Controller/ApiController.php","line":108,"function":"getRelatedToItem","class":"OCA\\RelatedResources\\Service\\RelatedService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"getRelatedResources","class":"OCA\\RelatedResources\\Controller\\ApiController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":65,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/ocs/v2.php","line":23,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/related_resources/lib/Service/RelatedService.php","Line":605,"message":"","exception":{},"CustomMessage":"Exception thrown: OCA\\RelatedResources\\Exceptions\\RelatedResourceProviderNotFound"}}
{"reqId":"cygCKNpraT3ZY3xKqoUf","level":3,"time":"2024-02-23T12:10:59+01:00","remoteAddr":"10.236.138.4","user":"admin","app":"related_resources","method":"GET","url":"/ocs/v2.php/apps/related_resources/related/account?itemId=admin&resourceType=deck&limit=5&format=json","message":"Exception thrown: OCA\\RelatedResources\\Exceptions\\RelatedResourceProviderNotFound","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0","version":"28.0.2.5","exception":{"Exception":"OCA\\RelatedResources\\Exceptions\\RelatedResourceProviderNotFound","Message":"","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/related_resources/lib/Service/RelatedService.php","line":173,"function":"getRelatedResourceProvider","class":"OCA\\RelatedResources\\Service\\RelatedService","type":"->"},{"file":"/var/www/nextcloud/apps/related_resources/lib/Service/RelatedService.php","line":127,"function":"retrieveRelatedToItem","class":"OCA\\RelatedResources\\Service\\RelatedService","type":"->"},{"file":"/var/www/nextcloud/apps/related_resources/lib/Controller/ApiController.php","line":108,"function":"getRelatedToItem","class":"OCA\\RelatedResources\\Service\\RelatedService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"getRelatedResources","class":"OCA\\RelatedResources\\Controller\\ApiController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":65,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/ocs/v2.php","line":23,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/related_resources/lib/Service/RelatedService.php","Line":605,"message":"","exception":{},"CustomMessage":"Exception thrown: OCA\\RelatedResources\\Exceptions\\RelatedResourceProviderNotFound"}}
{"reqId":"Qs30Jn8eE7UIl00VsKa6","level":3,"time":"2024-02-23T12:10:59+01:00","remoteAddr":"10.236.138.4","user":"admin","app":"related_resources","method":"GET","url":"/ocs/v2.php/apps/related_resources/related/account?itemId=admin&resourceType=calendar&limit=5&format=json","message":"Exception thrown: OCA\\RelatedResources\\Exceptions\\RelatedResourceProviderNotFound","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0","version":"28.0.2.5","exception":{"Exception":"OCA\\RelatedResources\\Exceptions\\RelatedResourceProviderNotFound","Message":"","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/related_resources/lib/Service/RelatedService.php","line":173,"function":"getRelatedResourceProvider","class":"OCA\\RelatedResources\\Service\\RelatedService","type":"->"},{"file":"/var/www/nextcloud/apps/related_resources/lib/Service/RelatedService.php","line":127,"function":"retrieveRelatedToItem","class":"OCA\\RelatedResources\\Service\\RelatedService","type":"->"},{"file":"/var/www/nextcloud/apps/related_resources/lib/Controller/ApiController.php","line":108,"function":"getRelatedToItem","class":"OCA\\RelatedResources\\Service\\RelatedService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"getRelatedResources","class":"OCA\\RelatedResources\\Controller\\ApiController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":65,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/ocs/v2.php","line":23,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/related_resources/lib/Service/RelatedService.php","Line":605,"message":"","exception":{},"CustomMessage":"Exception thrown: OCA\\RelatedResources\\Exceptions\\RelatedResourceProviderNotFound"}}
{"reqId":"kJWshCvpJxrHYACxhmgo","level":1,"time":"2024-02-23T12:11:47+01:00","remoteAddr":"","user":"--","app":"admin_audit","method":"","url":"--","message":"Console command executed: config:list system","userAgent":"--","version":"28.0.2.5","data":{"app":"admin_audit"}}
{"reqId":"GOH6CeZPgxQkRjMaRjim","level":1,"time":"2024-02-23T12:12:08+01:00","remoteAddr":"","user":"--","app":"admin_audit","method":"","url":"--","message":"Console command executed: app:list","userAgent":"--","version":"28.0.2.5","data":{"app":"admin_audit"}}
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by jmcclelland**
Fixes #362

### CODE REVIEW

**Comment by joshtrichards** [comment]
This would certainly help, but I think the root cause is the `NcRelatedResourcesPanel` component usage in the `Contacts` app:

https://github.com/nextcloud/contacts/blob/7a6a92af3b994fea8637bfe7eeaef9573ecd2dbe/src/components/ContactDetails.vue#L292

**Comment by Pytal** [comment]
Not familiar with contacts but on a quick look at the code the fix seems to be checking if the respective app for each `resource-type` is enabled before attempting to render it, cc @GretaD

**Review by GretaD — APPROVED** [review]

**Comment by GretaD** [comment]
thanks a lot for the contribution. Please sign your commit and we can merge it :)

**Comment by jmcclelland** [comment]
@GretaD Great - I just pushed my signature. Do you want me to rebase or merge-commit?

**Comment by jmcclelland** [comment]
@GretaD thanks - I just made the changes. Let me know if there is anything else for me to do.

**Comment by solracsf** [comment]
Is it possible to backport this?

**Pull request merged**
